let questionarray = [
  "POOPed?",
  "HOOPed?",
  "Been swiped by/swiped someone?",
  "Thrown shoes at choreographers?",
  "Learned house from Derek Zhang?",
  "Learned a piece from Genesis Garing?",
  "Sent/received a shoutout?",
  "Sent/received a thirsty shoutout?",
  "Sent a shoutout to every person on your team?",
  "Watched your group/casting videos?",
  "Wrote constructive feedback in the feedback form?",
  "Participated in a themed practice?",
  "Completed a secret buddy assignment?",
  "Got caught by your secret buddy?",
  "Participated in a joint team practice?",
  "Went to practice without eating?",
  "Went to practice without a water bottle?",
  "Yelled “car” in the parking lot?",
  "Practiced at Wooden for longer than 3 hours?",
  "Body rolled against the parking lot wall/floor?",
  "Forgot a teammate's name?",
  "Forgot choreography during groups/casting?",
  "Contributed to a team playlist?",
  "Gotten a sus nickname in the group chat?",
  "Went out of your way to get family points?",
  "Been photoshoot shopping with your team?",
  "Bought and returned a photoshoot outfit?",
  "Been to a social?",
  "Been to a joint social?",
  "Thought an “ice cream” social meant real ice cream?",
  "Prioritized dance before school/work?",
  "Went to a “study session” and didn't study?",
  "Broke something at a social?",
  "Squished in a car?",
  "Been to Meat Love with your team?",
  "Been to BCD with your team?",
  "Been to Marugame with your team?",
  "Been to a rooftop with your team?",
  "Watched a sunrise with your team?",
  "Pulled an all-nighter with a teammate?",
  "Been to your director’s FNF?",
  "Hosted a Foundations social?",
  "Received a noise complaint during a social?",
  "Had the landlord/police called on you?",
  "Had the landlord/police question you?",
  "Been on 2 Foundations team?",
  "Been on 3+ Foundations team?",
  "Been on 10 Foundations team? (Patrick Tran)",
  "Did 3 consecutive quarters of Foundations?",
  "Joined Foundations after you graduated?",
  "“Retired” from Foundations but joined another team?",
  "Thought about joining Dance LSHIP?",
  "Thought about joining Admin LSHIP?",
  "Been on Dance LSHIP?",
  "Been on Admin LSHIP?",
  "Started dancing in Foundations and came back as a director?",
  "Had a conversation with someone on Admin LSHIP?",
  "Had a conversation with all of Admin and Dance LSHIP?",
  "Wanted a Foundations LSHIP jacket?",
  "Watched old Foundations videos on Youtube?",
  "Considered doing a competitive team?",
  "Started dressing like a dancer?",
  "Used stoplight day for research purposes?",
  "Had a crush on a Foundations member?",
  "Had a crush on a LSHIP member?",
  "Hung out with a Foundations member alone?",
  "Been on a date with a Foundations member?",
  "Been in a relationship with a Foundations member?",
  "? (jk been in a couples piece?)",
  "Kissed a Foundations member?",
  "Made out with a Foundations member?",
  "Hooked up with a Foundations member?",
  "Participated in a Foundations Fundraiser?",
  "Have Foundations merch?",
  "Been to Foundations Office Hours?",
  "Been to Wintensive?",
  "Been to a Foundations Workshop?",
  "Been to all the workshops in a single quarter?",
  "Been to all Foundations events in a single quarter?",
  "Participated in Foundations Choreo Showcase?",
  "Performed at Lot 7?",
  "Performed at Ackerman Grand Ballroom?",
  "Been given a poster/flowers at showcase?",
  "Wore team gear the day after showcase?",
  "Fell in love with dance because of Foundations?",
  "Found a family in Foundations?",
  "Simped about your team before the quarter ended?",
  "Wrote love notes last minute?",
  "Gave a lap dance?",
  "Received a lap dance?",
  "Cried because of Foundations?",
  "Participated in a team reunion after the quarter ended?",
  "Participated in a team trip after the quarter ended?",
  "Drank on the hill?",
  "Yakked at an “ice cream” social?",
  "Took a team shot?",
  "Took a family shot?",
  "Used marijuana with a teammate?",
  "Used other substances with a teammate?",
  "Been kicked off a Foundations team?",
];

export default questionarray;
